/* eslint-disable @next/next/no-sync-scripts */
import Footer from "@/components/Footer/Footer";
import Headeter from "@/components/Header/Headeter";
import ToDoList from "@/components/ToDoList/ToDoList";
import TopNav from "@/components/TopNav/TopNav";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Todo | Redux Fundamental Example</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <div className="grid place-items-center bg-blue-100 h-screen px-6 font-sans">
        <TopNav />
        <div className="w-full max-w-3xl shadow-lg rounded-lg p-6 bg-white">
          <Headeter />
          <div className="mt-2 text-gray-700 text-sm max-h-[300px] overflow-y-auto">
            <ToDoList />
          </div>
          <Footer />
        </div>
      </div>
    </>
  );
}
